export const commentProperties = {
  address1: 'Address 1',
  address2: 'Address 2',
  agencyId: 'Agency Id',
  category: 'Category',
  city: 'City',
  comment: 'Comment',
  commentOn: 'Comment On',
  commentOnDocumentId: 'Comment on Document Id',
  country: 'Country',
  displayProperties: 'Display Properties',
  docAbstract: 'Doc Abstract',
  docketId: 'Docket Id',
  documentType: 'Document Type',
  duplicateComments: 'Duplicate Comments',
  email: 'Email',
  fax: 'Fax',
  field1: 'Field 1',
  field2: 'Field 2',
  fileFormats: 'File Formats',
  firstName: 'First Name',
  govAgency: 'Government Agency',
  govAgencyType: 'Government Agency Type',
  lastName: 'Last Name',
  legacyId: 'Legacy Id',
  modifyDate: 'Modify Date',
  objectId: 'Object Id',
  openForComment: 'Open for Comment',
  organization: 'Organization',
  originalDocumentId: 'Original Document Id',
  pageCount: 'Page Count',
  phone: 'Phone',
  postedDate: 'Posted Date',
  postmarkDate: 'Postmark Date',
  reasonWithdrawn: 'Reason Withdrawn',
  receiveDate: 'Receive Date',
  restrictReason: 'Restrict Reason',
  restrictReasonType: 'Restrict Reason Type',
  stateProvinceRegion: 'State Province Region',
  submitterRep: 'Submitter Rep',
  submitterRepAddress: 'Submitter Rep Address',
  submitterRepCityState: 'Submitted Rep City State',
  subtype: 'Subtype',
  title: 'Title',
  trackingNbr: 'Tracking Number',
  withdrawn: 'Withdrawn',
  zip: 'Zip',
};

export const formatDate = (date) => date.toLocaleString('en-US');
